#程序启动监听的端口号
port: 8080
#线程池数量
threadPoolSize: 100
#默认转发规则
defaultForward: "172.18.1.50:80"

#是否根据请求开启IP转发  ip转发和客户端协议转发互斥   当两个都开启的时候，以IP转发为准

#根据客户端请求ip转发
ipForward:
  enable: false
  forward:
    #如果客户端请求IP为  172.18.1.50  或者 172.18.1.18  则转发到172.18.1.50:3000
    "172.18.1.50:3000":
      - "172.18.1.50"
      - "172.18.1.12"
    "172.18.1.50:22":
      - "127.0.0.1"

#是否开启客户端协议转发   ip转发和客户端协议转发互斥
clientProtocolForward:
  enable: true
  #客户端协议转发规则
 #协议转发 客户端请求协议为  http 则转发到172.18.1.50:80  ssh 则转发到172.18.1.50:22
  protocols:
    http: "172.18.1.50:3000"
    https: "www.baidu.com:443"
    ssh: "172.18.1.50:22"
    mysql: "127.0.0.1:3306"

